site_name: A Data Scientists guide to software engineering
site_description: A catalogue of software engineering principles

nav:
  - Home: index.md
  - Data Pipeline:
    - SQL Pipeline Documentation: sql_docs.md
  - Training:
    - Python Scripts: docstring_example.md
    - Jupyter Notebooks: notebook_example.ipynb

plugins:
  - search
  - autorefs
  - mkdocs-jupyter
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
          setup_commands:
            - import sys
            - sys.path.append('../')

theme:
  name: material
  feature:
    - tabs: true
    - announce.dismiss
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - content.action.edit

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
